# Generated by the protocol buffer compiler.  DO NOT EDIT!

from google.protobuf import descriptor
from google.protobuf import message
from google.protobuf import reflection
from google.protobuf import service
from google.protobuf import service_reflection
from google.protobuf import descriptor_pb2


_BASEMESSAGE_COMMANDTYPE = descriptor.EnumDescriptor(
  name='CommandType',
  full_name='com.activequant.messages.BaseMessage.CommandType',
  filename='CommandType',
  values=[
    descriptor.EnumValueDescriptor(
      name='VERSION', index=0, number=1,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='LOGIN', index=1, number=2,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='SERVER_TIME', index=2, number=3,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='LOGIN_RESPONSE', index=3, number=4,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='MDS', index=4, number=5,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='ACCT_DATA', index=5, number=6,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='POSITION_REPORT', index=6, number=7,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='EXECUTION_REPORT', index=7, number=8,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='ORD_CNCL_REQ', index=8, number=9,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='ORD_CNCL_REJ', index=9, number=10,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='ORD_CNCL_REPL_REQ', index=10, number=11,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='NEW_ORDER', index=11, number=12,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='ORD_SUBMITTED', index=12, number=13,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='ORD_ACCPTD', index=13, number=14,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='ORD_CANCELLED', index=14, number=15,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='ORD_UPDATED', index=15, number=16,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='SECURITY_STATUS', index=16, number=17,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='ORD_REJ', index=17, number=18,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='ORD_UPDATE_SUBMITTED', index=18, number=19,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='ORD_CANCEL_SUBMITTED', index=19, number=20,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='ORD_UPD_REJECTED', index=20, number=21,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='EXECUTION_REPORT2', index=21, number=22,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='CUST_CMD', index=22, number=23,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='INFO_EVENT', index=23, number=24,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='OHLC', index=24, number=25,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='TICK', index=25, number=26,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='VALUESET', index=26, number=27,
      options=None,
      type=None),
  ],
  options=None,
)


_BASEMESSAGE = descriptor.Descriptor(
  name='BaseMessage',
  full_name='com.activequant.messages.BaseMessage',
  filename='messages.proto',
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='type', full_name='com.activequant.messages.BaseMessage.type', index=0,
      number=1, type=14, cpp_type=8, label=2,
      default_value=1,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],  # TODO(robinson): Implement.
  enum_types=[
    _BASEMESSAGE_COMMANDTYPE,
  ],
  options=None)


_LOGIN = descriptor.Descriptor(
  name='Login',
  full_name='com.activequant.messages.Login',
  filename='messages.proto',
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='userId', full_name='com.activequant.messages.Login.userId', index=0,
      number=1, type=9, cpp_type=9, label=2,
      default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='password', full_name='com.activequant.messages.Login.password', index=1,
      number=2, type=9, cpp_type=9, label=2,
      default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='sessionType', full_name='com.activequant.messages.Login.sessionType', index=2,
      number=3, type=9, cpp_type=9, label=2,
      default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
    descriptor.FieldDescriptor(
      name='cmd', full_name='com.activequant.messages.Login.cmd', index=0,
      number=100, type=11, cpp_type=10, label=2,
      default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=True, extension_scope=None,
      options=None),
  ],
  nested_types=[],  # TODO(robinson): Implement.
  enum_types=[
  ],
  options=None)


_SERVERTIME = descriptor.Descriptor(
  name='ServerTime',
  full_name='com.activequant.messages.ServerTime',
  filename='messages.proto',
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='timestamp', full_name='com.activequant.messages.ServerTime.timestamp', index=0,
      number=1, type=3, cpp_type=2, label=2,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
    descriptor.FieldDescriptor(
      name='cmd', full_name='com.activequant.messages.ServerTime.cmd', index=0,
      number=101, type=11, cpp_type=10, label=2,
      default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=True, extension_scope=None,
      options=None),
  ],
  nested_types=[],  # TODO(robinson): Implement.
  enum_types=[
  ],
  options=None)


_LOGINRESPONSE = descriptor.Descriptor(
  name='LoginResponse',
  full_name='com.activequant.messages.LoginResponse',
  filename='messages.proto',
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='status', full_name='com.activequant.messages.LoginResponse.status', index=0,
      number=1, type=9, cpp_type=9, label=2,
      default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
    descriptor.FieldDescriptor(
      name='cmd', full_name='com.activequant.messages.LoginResponse.cmd', index=0,
      number=102, type=11, cpp_type=10, label=2,
      default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=True, extension_scope=None,
      options=None),
  ],
  nested_types=[],  # TODO(robinson): Implement.
  enum_types=[
  ],
  options=None)


_MARKETDATASNAPSHOT = descriptor.Descriptor(
  name='MarketDataSnapshot',
  full_name='com.activequant.messages.MarketDataSnapshot',
  filename='messages.proto',
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='timestamp', full_name='com.activequant.messages.MarketDataSnapshot.timestamp', index=0,
      number=1, type=3, cpp_type=2, label=2,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='bidPx', full_name='com.activequant.messages.MarketDataSnapshot.bidPx', index=1,
      number=2, type=1, cpp_type=5, label=3,
      default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='askPx', full_name='com.activequant.messages.MarketDataSnapshot.askPx', index=2,
      number=3, type=1, cpp_type=5, label=3,
      default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='bidQ', full_name='com.activequant.messages.MarketDataSnapshot.bidQ', index=3,
      number=4, type=1, cpp_type=5, label=3,
      default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='askQ', full_name='com.activequant.messages.MarketDataSnapshot.askQ', index=4,
      number=5, type=1, cpp_type=5, label=3,
      default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='mdiId', full_name='com.activequant.messages.MarketDataSnapshot.mdiId', index=5,
      number=6, type=9, cpp_type=9, label=2,
      default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='resend', full_name='com.activequant.messages.MarketDataSnapshot.resend', index=6,
      number=7, type=8, cpp_type=7, label=1,
      default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
    descriptor.FieldDescriptor(
      name='cmd', full_name='com.activequant.messages.MarketDataSnapshot.cmd', index=0,
      number=103, type=11, cpp_type=10, label=2,
      default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=True, extension_scope=None,
      options=None),
  ],
  nested_types=[],  # TODO(robinson): Implement.
  enum_types=[
  ],
  options=None)


_ACCOUNTDATAMESSAGE = descriptor.Descriptor(
  name='AccountDataMessage',
  full_name='com.activequant.messages.AccountDataMessage',
  filename='messages.proto',
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='type', full_name='com.activequant.messages.AccountDataMessage.type', index=0,
      number=1, type=9, cpp_type=9, label=2,
      default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='value', full_name='com.activequant.messages.AccountDataMessage.value', index=1,
      number=2, type=9, cpp_type=9, label=2,
      default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
    descriptor.FieldDescriptor(
      name='cmd', full_name='com.activequant.messages.AccountDataMessage.cmd', index=0,
      number=104, type=11, cpp_type=10, label=2,
      default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=True, extension_scope=None,
      options=None),
  ],
  nested_types=[],  # TODO(robinson): Implement.
  enum_types=[
  ],
  options=None)


_POSITIONREPORT = descriptor.Descriptor(
  name='PositionReport',
  full_name='com.activequant.messages.PositionReport',
  filename='messages.proto',
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='openDate', full_name='com.activequant.messages.PositionReport.openDate', index=0,
      number=1, type=9, cpp_type=9, label=2,
      default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='entryPrice', full_name='com.activequant.messages.PositionReport.entryPrice', index=1,
      number=2, type=1, cpp_type=5, label=2,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='quantity', full_name='com.activequant.messages.PositionReport.quantity', index=2,
      number=3, type=1, cpp_type=5, label=2,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='tradInstId', full_name='com.activequant.messages.PositionReport.tradInstId', index=3,
      number=4, type=9, cpp_type=9, label=2,
      default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
    descriptor.FieldDescriptor(
      name='cmd', full_name='com.activequant.messages.PositionReport.cmd', index=0,
      number=105, type=11, cpp_type=10, label=2,
      default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=True, extension_scope=None,
      options=None),
  ],
  nested_types=[],  # TODO(robinson): Implement.
  enum_types=[
  ],
  options=None)


_EXECUTIONREPORT = descriptor.Descriptor(
  name='ExecutionReport',
  full_name='com.activequant.messages.ExecutionReport',
  filename='messages.proto',
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='clOrdId', full_name='com.activequant.messages.ExecutionReport.clOrdId', index=0,
      number=1, type=9, cpp_type=9, label=2,
      default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='execId', full_name='com.activequant.messages.ExecutionReport.execId', index=1,
      number=2, type=9, cpp_type=9, label=2,
      default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='side', full_name='com.activequant.messages.ExecutionReport.side', index=2,
      number=3, type=5, cpp_type=1, label=2,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='currency', full_name='com.activequant.messages.ExecutionReport.currency', index=3,
      number=4, type=9, cpp_type=9, label=2,
      default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='orderQty', full_name='com.activequant.messages.ExecutionReport.orderQty', index=4,
      number=5, type=1, cpp_type=5, label=2,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='price', full_name='com.activequant.messages.ExecutionReport.price', index=5,
      number=6, type=1, cpp_type=5, label=2,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='tradInstId', full_name='com.activequant.messages.ExecutionReport.tradInstId', index=6,
      number=7, type=9, cpp_type=9, label=2,
      default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='transactTime', full_name='com.activequant.messages.ExecutionReport.transactTime', index=7,
      number=8, type=9, cpp_type=9, label=2,
      default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='orderId', full_name='com.activequant.messages.ExecutionReport.orderId', index=8,
      number=9, type=9, cpp_type=9, label=2,
      default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='execType', full_name='com.activequant.messages.ExecutionReport.execType', index=9,
      number=10, type=5, cpp_type=1, label=2,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='ordStatus', full_name='com.activequant.messages.ExecutionReport.ordStatus', index=10,
      number=11, type=5, cpp_type=1, label=2,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='cumQty', full_name='com.activequant.messages.ExecutionReport.cumQty', index=11,
      number=12, type=1, cpp_type=5, label=2,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='leavesQty', full_name='com.activequant.messages.ExecutionReport.leavesQty', index=12,
      number=13, type=1, cpp_type=5, label=2,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='avgPx', full_name='com.activequant.messages.ExecutionReport.avgPx', index=13,
      number=14, type=1, cpp_type=5, label=2,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='ordType', full_name='com.activequant.messages.ExecutionReport.ordType', index=14,
      number=16, type=9, cpp_type=9, label=2,
      default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='text', full_name='com.activequant.messages.ExecutionReport.text', index=15,
      number=17, type=9, cpp_type=9, label=1,
      default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='comment', full_name='com.activequant.messages.ExecutionReport.comment', index=16,
      number=19, type=9, cpp_type=9, label=1,
      default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
    descriptor.FieldDescriptor(
      name='cmd', full_name='com.activequant.messages.ExecutionReport.cmd', index=0,
      number=106, type=11, cpp_type=10, label=2,
      default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=True, extension_scope=None,
      options=None),
  ],
  nested_types=[],  # TODO(robinson): Implement.
  enum_types=[
  ],
  options=None)


_ORDERCANCELREQUEST = descriptor.Descriptor(
  name='OrderCancelRequest',
  full_name='com.activequant.messages.OrderCancelRequest',
  filename='messages.proto',
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='orgCldOrdId', full_name='com.activequant.messages.OrderCancelRequest.orgCldOrdId', index=0,
      number=1, type=9, cpp_type=9, label=2,
      default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='clOrdId', full_name='com.activequant.messages.OrderCancelRequest.clOrdId', index=1,
      number=2, type=9, cpp_type=9, label=2,
      default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='tradInstId', full_name='com.activequant.messages.OrderCancelRequest.tradInstId', index=2,
      number=3, type=9, cpp_type=9, label=2,
      default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='side', full_name='com.activequant.messages.OrderCancelRequest.side', index=3,
      number=4, type=5, cpp_type=1, label=2,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='orderQty', full_name='com.activequant.messages.OrderCancelRequest.orderQty', index=4,
      number=6, type=1, cpp_type=5, label=2,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='comment', full_name='com.activequant.messages.OrderCancelRequest.comment', index=5,
      number=19, type=9, cpp_type=9, label=1,
      default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
    descriptor.FieldDescriptor(
      name='cmd', full_name='com.activequant.messages.OrderCancelRequest.cmd', index=0,
      number=107, type=11, cpp_type=10, label=2,
      default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=True, extension_scope=None,
      options=None),
  ],
  nested_types=[],  # TODO(robinson): Implement.
  enum_types=[
  ],
  options=None)


_ORDERCANCELREJECT = descriptor.Descriptor(
  name='OrderCancelReject',
  full_name='com.activequant.messages.OrderCancelReject',
  filename='messages.proto',
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='tradInstId', full_name='com.activequant.messages.OrderCancelReject.tradInstId', index=0,
      number=1, type=9, cpp_type=9, label=2,
      default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='clOrdId', full_name='com.activequant.messages.OrderCancelReject.clOrdId', index=1,
      number=2, type=9, cpp_type=9, label=2,
      default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='orgClOrdId', full_name='com.activequant.messages.OrderCancelReject.orgClOrdId', index=2,
      number=3, type=9, cpp_type=9, label=2,
      default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='ordStatus', full_name='com.activequant.messages.OrderCancelReject.ordStatus', index=3,
      number=4, type=9, cpp_type=9, label=2,
      default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='CxlRejResponseTo', full_name='com.activequant.messages.OrderCancelReject.CxlRejResponseTo', index=4,
      number=5, type=9, cpp_type=9, label=2,
      default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='clxRejReason', full_name='com.activequant.messages.OrderCancelReject.clxRejReason', index=5,
      number=6, type=9, cpp_type=9, label=1,
      default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='text', full_name='com.activequant.messages.OrderCancelReject.text', index=6,
      number=7, type=9, cpp_type=9, label=1,
      default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='comment', full_name='com.activequant.messages.OrderCancelReject.comment', index=7,
      number=19, type=9, cpp_type=9, label=1,
      default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
    descriptor.FieldDescriptor(
      name='cmd', full_name='com.activequant.messages.OrderCancelReject.cmd', index=0,
      number=108, type=11, cpp_type=10, label=2,
      default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=True, extension_scope=None,
      options=None),
  ],
  nested_types=[],  # TODO(robinson): Implement.
  enum_types=[
  ],
  options=None)


_ORDERCANCELREPLACEREQUEST = descriptor.Descriptor(
  name='OrderCancelReplaceRequest',
  full_name='com.activequant.messages.OrderCancelReplaceRequest',
  filename='messages.proto',
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='tradInstId', full_name='com.activequant.messages.OrderCancelReplaceRequest.tradInstId', index=0,
      number=1, type=9, cpp_type=9, label=2,
      default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='clOrdId', full_name='com.activequant.messages.OrderCancelReplaceRequest.clOrdId', index=1,
      number=2, type=9, cpp_type=9, label=2,
      default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='orgClOrdId', full_name='com.activequant.messages.OrderCancelReplaceRequest.orgClOrdId', index=2,
      number=3, type=9, cpp_type=9, label=2,
      default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='side', full_name='com.activequant.messages.OrderCancelReplaceRequest.side', index=3,
      number=4, type=5, cpp_type=1, label=2,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='transactTime', full_name='com.activequant.messages.OrderCancelReplaceRequest.transactTime', index=4,
      number=5, type=9, cpp_type=9, label=2,
      default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='orderQty', full_name='com.activequant.messages.OrderCancelReplaceRequest.orderQty', index=5,
      number=6, type=1, cpp_type=5, label=2,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='ordType', full_name='com.activequant.messages.OrderCancelReplaceRequest.ordType', index=6,
      number=7, type=5, cpp_type=1, label=2,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='price', full_name='com.activequant.messages.OrderCancelReplaceRequest.price', index=7,
      number=8, type=1, cpp_type=5, label=2,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='timeInForce', full_name='com.activequant.messages.OrderCancelReplaceRequest.timeInForce', index=8,
      number=9, type=5, cpp_type=1, label=2,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='comment', full_name='com.activequant.messages.OrderCancelReplaceRequest.comment', index=9,
      number=19, type=9, cpp_type=9, label=1,
      default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
    descriptor.FieldDescriptor(
      name='cmd', full_name='com.activequant.messages.OrderCancelReplaceRequest.cmd', index=0,
      number=109, type=11, cpp_type=10, label=2,
      default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=True, extension_scope=None,
      options=None),
  ],
  nested_types=[],  # TODO(robinson): Implement.
  enum_types=[
  ],
  options=None)


_NEWORDER = descriptor.Descriptor(
  name='NewOrder',
  full_name='com.activequant.messages.NewOrder',
  filename='messages.proto',
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='tradInstId', full_name='com.activequant.messages.NewOrder.tradInstId', index=0,
      number=1, type=9, cpp_type=9, label=2,
      default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='clOrdId', full_name='com.activequant.messages.NewOrder.clOrdId', index=1,
      number=2, type=9, cpp_type=9, label=2,
      default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='orgClOrdId', full_name='com.activequant.messages.NewOrder.orgClOrdId', index=2,
      number=3, type=9, cpp_type=9, label=1,
      default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='side', full_name='com.activequant.messages.NewOrder.side', index=3,
      number=4, type=5, cpp_type=1, label=2,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='transactTime', full_name='com.activequant.messages.NewOrder.transactTime', index=4,
      number=5, type=9, cpp_type=9, label=1,
      default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='orderQty', full_name='com.activequant.messages.NewOrder.orderQty', index=5,
      number=6, type=1, cpp_type=5, label=2,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='ordType', full_name='com.activequant.messages.NewOrder.ordType', index=6,
      number=7, type=5, cpp_type=1, label=2,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='price', full_name='com.activequant.messages.NewOrder.price', index=7,
      number=8, type=1, cpp_type=5, label=1,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='timeInForce', full_name='com.activequant.messages.NewOrder.timeInForce', index=8,
      number=9, type=5, cpp_type=1, label=1,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='comment', full_name='com.activequant.messages.NewOrder.comment', index=9,
      number=19, type=9, cpp_type=9, label=1,
      default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='resend', full_name='com.activequant.messages.NewOrder.resend', index=10,
      number=20, type=5, cpp_type=1, label=2,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
    descriptor.FieldDescriptor(
      name='cmd', full_name='com.activequant.messages.NewOrder.cmd', index=0,
      number=110, type=11, cpp_type=10, label=2,
      default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=True, extension_scope=None,
      options=None),
  ],
  nested_types=[],  # TODO(robinson): Implement.
  enum_types=[
  ],
  options=None)


_ORDERSUBMITTED = descriptor.Descriptor(
  name='OrderSubmitted',
  full_name='com.activequant.messages.OrderSubmitted',
  filename='messages.proto',
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='clOrdId', full_name='com.activequant.messages.OrderSubmitted.clOrdId', index=0,
      number=2, type=9, cpp_type=9, label=2,
      default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
    descriptor.FieldDescriptor(
      name='cmd', full_name='com.activequant.messages.OrderSubmitted.cmd', index=0,
      number=111, type=11, cpp_type=10, label=2,
      default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=True, extension_scope=None,
      options=None),
  ],
  nested_types=[],  # TODO(robinson): Implement.
  enum_types=[
  ],
  options=None)


_ORDERACCEPTED = descriptor.Descriptor(
  name='OrderAccepted',
  full_name='com.activequant.messages.OrderAccepted',
  filename='messages.proto',
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='clOrdId', full_name='com.activequant.messages.OrderAccepted.clOrdId', index=0,
      number=2, type=9, cpp_type=9, label=2,
      default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
    descriptor.FieldDescriptor(
      name='cmd', full_name='com.activequant.messages.OrderAccepted.cmd', index=0,
      number=112, type=11, cpp_type=10, label=2,
      default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=True, extension_scope=None,
      options=None),
  ],
  nested_types=[],  # TODO(robinson): Implement.
  enum_types=[
  ],
  options=None)


_ORDERCANCELLED = descriptor.Descriptor(
  name='OrderCancelled',
  full_name='com.activequant.messages.OrderCancelled',
  filename='messages.proto',
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='clOrdId', full_name='com.activequant.messages.OrderCancelled.clOrdId', index=0,
      number=2, type=9, cpp_type=9, label=2,
      default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
    descriptor.FieldDescriptor(
      name='cmd', full_name='com.activequant.messages.OrderCancelled.cmd', index=0,
      number=113, type=11, cpp_type=10, label=2,
      default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=True, extension_scope=None,
      options=None),
  ],
  nested_types=[],  # TODO(robinson): Implement.
  enum_types=[
  ],
  options=None)


_ORDERUPDATED = descriptor.Descriptor(
  name='OrderUpdated',
  full_name='com.activequant.messages.OrderUpdated',
  filename='messages.proto',
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='clOrdId', full_name='com.activequant.messages.OrderUpdated.clOrdId', index=0,
      number=2, type=9, cpp_type=9, label=2,
      default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
    descriptor.FieldDescriptor(
      name='cmd', full_name='com.activequant.messages.OrderUpdated.cmd', index=0,
      number=114, type=11, cpp_type=10, label=2,
      default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=True, extension_scope=None,
      options=None),
  ],
  nested_types=[],  # TODO(robinson): Implement.
  enum_types=[
  ],
  options=None)


_SECURITYSTATUS = descriptor.Descriptor(
  name='SecurityStatus',
  full_name='com.activequant.messages.SecurityStatus',
  filename='messages.proto',
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='tdiId', full_name='com.activequant.messages.SecurityStatus.tdiId', index=0,
      number=2, type=9, cpp_type=9, label=2,
      default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='status', full_name='com.activequant.messages.SecurityStatus.status', index=1,
      number=3, type=9, cpp_type=9, label=2,
      default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
    descriptor.FieldDescriptor(
      name='cmd', full_name='com.activequant.messages.SecurityStatus.cmd', index=0,
      number=115, type=11, cpp_type=10, label=2,
      default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=True, extension_scope=None,
      options=None),
  ],
  nested_types=[],  # TODO(robinson): Implement.
  enum_types=[
  ],
  options=None)


_ORDERREJECTED = descriptor.Descriptor(
  name='OrderRejected',
  full_name='com.activequant.messages.OrderRejected',
  filename='messages.proto',
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='clOrdId', full_name='com.activequant.messages.OrderRejected.clOrdId', index=0,
      number=2, type=9, cpp_type=9, label=2,
      default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='reason', full_name='com.activequant.messages.OrderRejected.reason', index=1,
      number=3, type=9, cpp_type=9, label=2,
      default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
    descriptor.FieldDescriptor(
      name='cmd', full_name='com.activequant.messages.OrderRejected.cmd', index=0,
      number=116, type=11, cpp_type=10, label=2,
      default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=True, extension_scope=None,
      options=None),
  ],
  nested_types=[],  # TODO(robinson): Implement.
  enum_types=[
  ],
  options=None)


_ORDERUPDATESUBMITTED = descriptor.Descriptor(
  name='OrderUpdateSubmitted',
  full_name='com.activequant.messages.OrderUpdateSubmitted',
  filename='messages.proto',
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='clOrdId', full_name='com.activequant.messages.OrderUpdateSubmitted.clOrdId', index=0,
      number=2, type=9, cpp_type=9, label=2,
      default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
    descriptor.FieldDescriptor(
      name='cmd', full_name='com.activequant.messages.OrderUpdateSubmitted.cmd', index=0,
      number=117, type=11, cpp_type=10, label=2,
      default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=True, extension_scope=None,
      options=None),
  ],
  nested_types=[],  # TODO(robinson): Implement.
  enum_types=[
  ],
  options=None)


_ORDERCANCELSUBMITTED = descriptor.Descriptor(
  name='OrderCancelSubmitted',
  full_name='com.activequant.messages.OrderCancelSubmitted',
  filename='messages.proto',
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='clOrdId', full_name='com.activequant.messages.OrderCancelSubmitted.clOrdId', index=0,
      number=2, type=9, cpp_type=9, label=2,
      default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
    descriptor.FieldDescriptor(
      name='cmd', full_name='com.activequant.messages.OrderCancelSubmitted.cmd', index=0,
      number=118, type=11, cpp_type=10, label=2,
      default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=True, extension_scope=None,
      options=None),
  ],
  nested_types=[],  # TODO(robinson): Implement.
  enum_types=[
  ],
  options=None)


_ORDERUPDATEREJECTED = descriptor.Descriptor(
  name='OrderUpdateRejected',
  full_name='com.activequant.messages.OrderUpdateRejected',
  filename='messages.proto',
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='clOrdId', full_name='com.activequant.messages.OrderUpdateRejected.clOrdId', index=0,
      number=2, type=9, cpp_type=9, label=2,
      default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='reason', full_name='com.activequant.messages.OrderUpdateRejected.reason', index=1,
      number=3, type=9, cpp_type=9, label=2,
      default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
    descriptor.FieldDescriptor(
      name='cmd', full_name='com.activequant.messages.OrderUpdateRejected.cmd', index=0,
      number=119, type=11, cpp_type=10, label=2,
      default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=True, extension_scope=None,
      options=None),
  ],
  nested_types=[],  # TODO(robinson): Implement.
  enum_types=[
  ],
  options=None)


_EXECUTIONREPORT2 = descriptor.Descriptor(
  name='ExecutionReport2',
  full_name='com.activequant.messages.ExecutionReport2',
  filename='messages.proto',
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='clOrdId', full_name='com.activequant.messages.ExecutionReport2.clOrdId', index=0,
      number=1, type=9, cpp_type=9, label=2,
      default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='execId', full_name='com.activequant.messages.ExecutionReport2.execId', index=1,
      number=2, type=9, cpp_type=9, label=2,
      default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='side', full_name='com.activequant.messages.ExecutionReport2.side', index=2,
      number=3, type=9, cpp_type=9, label=2,
      default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='price', full_name='com.activequant.messages.ExecutionReport2.price', index=3,
      number=6, type=1, cpp_type=5, label=2,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='tdiId', full_name='com.activequant.messages.ExecutionReport2.tdiId', index=4,
      number=7, type=9, cpp_type=9, label=2,
      default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='transactTime', full_name='com.activequant.messages.ExecutionReport2.transactTime', index=5,
      number=8, type=3, cpp_type=2, label=2,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='qty', full_name='com.activequant.messages.ExecutionReport2.qty', index=6,
      number=13, type=1, cpp_type=5, label=2,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='resend', full_name='com.activequant.messages.ExecutionReport2.resend', index=7,
      number=14, type=5, cpp_type=1, label=2,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='quantityLeft', full_name='com.activequant.messages.ExecutionReport2.quantityLeft', index=8,
      number=15, type=1, cpp_type=5, label=2,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
    descriptor.FieldDescriptor(
      name='cmd', full_name='com.activequant.messages.ExecutionReport2.cmd', index=0,
      number=120, type=11, cpp_type=10, label=2,
      default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=True, extension_scope=None,
      options=None),
  ],
  nested_types=[],  # TODO(robinson): Implement.
  enum_types=[
  ],
  options=None)


_CUSTOMCOMMAND = descriptor.Descriptor(
  name='CustomCommand',
  full_name='com.activequant.messages.CustomCommand',
  filename='messages.proto',
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='command', full_name='com.activequant.messages.CustomCommand.command', index=0,
      number=1, type=9, cpp_type=9, label=2,
      default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
    descriptor.FieldDescriptor(
      name='cmd', full_name='com.activequant.messages.CustomCommand.cmd', index=0,
      number=121, type=11, cpp_type=10, label=2,
      default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=True, extension_scope=None,
      options=None),
  ],
  nested_types=[],  # TODO(robinson): Implement.
  enum_types=[
  ],
  options=None)


_INFOEVENT = descriptor.Descriptor(
  name='InfoEvent',
  full_name='com.activequant.messages.InfoEvent',
  filename='messages.proto',
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='message', full_name='com.activequant.messages.InfoEvent.message', index=0,
      number=1, type=9, cpp_type=9, label=2,
      default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='timestamp', full_name='com.activequant.messages.InfoEvent.timestamp', index=1,
      number=2, type=3, cpp_type=2, label=2,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
    descriptor.FieldDescriptor(
      name='cmd', full_name='com.activequant.messages.InfoEvent.cmd', index=0,
      number=122, type=11, cpp_type=10, label=2,
      default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=True, extension_scope=None,
      options=None),
  ],
  nested_types=[],  # TODO(robinson): Implement.
  enum_types=[
  ],
  options=None)


_OHLC = descriptor.Descriptor(
  name='OHLC',
  full_name='com.activequant.messages.OHLC',
  filename='messages.proto',
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='timestamp', full_name='com.activequant.messages.OHLC.timestamp', index=0,
      number=1, type=3, cpp_type=2, label=2,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='mdiId', full_name='com.activequant.messages.OHLC.mdiId', index=1,
      number=2, type=9, cpp_type=9, label=2,
      default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='open', full_name='com.activequant.messages.OHLC.open', index=2,
      number=3, type=1, cpp_type=5, label=2,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='high', full_name='com.activequant.messages.OHLC.high', index=3,
      number=4, type=1, cpp_type=5, label=2,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='low', full_name='com.activequant.messages.OHLC.low', index=4,
      number=5, type=1, cpp_type=5, label=2,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='close', full_name='com.activequant.messages.OHLC.close', index=5,
      number=6, type=1, cpp_type=5, label=2,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='volume', full_name='com.activequant.messages.OHLC.volume', index=6,
      number=7, type=1, cpp_type=5, label=1,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
    descriptor.FieldDescriptor(
      name='cmd', full_name='com.activequant.messages.OHLC.cmd', index=0,
      number=123, type=11, cpp_type=10, label=2,
      default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=True, extension_scope=None,
      options=None),
  ],
  nested_types=[],  # TODO(robinson): Implement.
  enum_types=[
  ],
  options=None)


_TICK = descriptor.Descriptor(
  name='Tick',
  full_name='com.activequant.messages.Tick',
  filename='messages.proto',
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='timestamp', full_name='com.activequant.messages.Tick.timestamp', index=0,
      number=1, type=3, cpp_type=2, label=2,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='mdiId', full_name='com.activequant.messages.Tick.mdiId', index=1,
      number=2, type=9, cpp_type=9, label=2,
      default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='price', full_name='com.activequant.messages.Tick.price', index=2,
      number=3, type=1, cpp_type=5, label=2,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='quantity', full_name='com.activequant.messages.Tick.quantity', index=3,
      number=4, type=1, cpp_type=5, label=2,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='tickDirection', full_name='com.activequant.messages.Tick.tickDirection', index=4,
      number=5, type=5, cpp_type=1, label=2,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
    descriptor.FieldDescriptor(
      name='cmd', full_name='com.activequant.messages.Tick.cmd', index=0,
      number=124, type=11, cpp_type=10, label=2,
      default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=True, extension_scope=None,
      options=None),
  ],
  nested_types=[],  # TODO(robinson): Implement.
  enum_types=[
  ],
  options=None)


_VALUESET = descriptor.Descriptor(
  name='ValueSet',
  full_name='com.activequant.messages.ValueSet',
  filename='messages.proto',
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='timestamp', full_name='com.activequant.messages.ValueSet.timestamp', index=0,
      number=1, type=3, cpp_type=2, label=2,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='type', full_name='com.activequant.messages.ValueSet.type', index=1,
      number=2, type=9, cpp_type=9, label=2,
      default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='id', full_name='com.activequant.messages.ValueSet.id', index=2,
      number=3, type=9, cpp_type=9, label=2,
      default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='field', full_name='com.activequant.messages.ValueSet.field', index=3,
      number=4, type=9, cpp_type=9, label=2,
      default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='value', full_name='com.activequant.messages.ValueSet.value', index=4,
      number=5, type=9, cpp_type=9, label=2,
      default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
    descriptor.FieldDescriptor(
      name='cmd', full_name='com.activequant.messages.ValueSet.cmd', index=0,
      number=125, type=11, cpp_type=10, label=2,
      default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=True, extension_scope=None,
      options=None),
  ],
  nested_types=[],  # TODO(robinson): Implement.
  enum_types=[
  ],
  options=None)


_BASEMESSAGE.fields_by_name['type'].enum_type = _BASEMESSAGE_COMMANDTYPE

class BaseMessage(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _BASEMESSAGE

class Login(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _LOGIN

class ServerTime(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _SERVERTIME

class LoginResponse(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _LOGINRESPONSE

class MarketDataSnapshot(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _MARKETDATASNAPSHOT

class AccountDataMessage(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _ACCOUNTDATAMESSAGE

class PositionReport(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _POSITIONREPORT

class ExecutionReport(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _EXECUTIONREPORT

class OrderCancelRequest(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _ORDERCANCELREQUEST

class OrderCancelReject(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _ORDERCANCELREJECT

class OrderCancelReplaceRequest(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _ORDERCANCELREPLACEREQUEST

class NewOrder(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _NEWORDER

class OrderSubmitted(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _ORDERSUBMITTED

class OrderAccepted(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _ORDERACCEPTED

class OrderCancelled(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _ORDERCANCELLED

class OrderUpdated(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _ORDERUPDATED

class SecurityStatus(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _SECURITYSTATUS

class OrderRejected(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _ORDERREJECTED

class OrderUpdateSubmitted(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _ORDERUPDATESUBMITTED

class OrderCancelSubmitted(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _ORDERCANCELSUBMITTED

class OrderUpdateRejected(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _ORDERUPDATEREJECTED

class ExecutionReport2(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _EXECUTIONREPORT2

class CustomCommand(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _CUSTOMCOMMAND

class InfoEvent(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _INFOEVENT

class OHLC(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _OHLC

class Tick(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _TICK

class ValueSet(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _VALUESET

_LOGIN.extensions_by_name['cmd'].message_type = _LOGIN
BaseMessage.RegisterExtension(_LOGIN.extensions_by_name['cmd'])
_SERVERTIME.extensions_by_name['cmd'].message_type = _SERVERTIME
BaseMessage.RegisterExtension(_SERVERTIME.extensions_by_name['cmd'])
_LOGINRESPONSE.extensions_by_name['cmd'].message_type = _LOGINRESPONSE
BaseMessage.RegisterExtension(_LOGINRESPONSE.extensions_by_name['cmd'])
_MARKETDATASNAPSHOT.extensions_by_name['cmd'].message_type = _MARKETDATASNAPSHOT
BaseMessage.RegisterExtension(_MARKETDATASNAPSHOT.extensions_by_name['cmd'])
_ACCOUNTDATAMESSAGE.extensions_by_name['cmd'].message_type = _ACCOUNTDATAMESSAGE
BaseMessage.RegisterExtension(_ACCOUNTDATAMESSAGE.extensions_by_name['cmd'])
_POSITIONREPORT.extensions_by_name['cmd'].message_type = _POSITIONREPORT
BaseMessage.RegisterExtension(_POSITIONREPORT.extensions_by_name['cmd'])
_EXECUTIONREPORT.extensions_by_name['cmd'].message_type = _EXECUTIONREPORT
BaseMessage.RegisterExtension(_EXECUTIONREPORT.extensions_by_name['cmd'])
_ORDERCANCELREQUEST.extensions_by_name['cmd'].message_type = _ORDERCANCELREQUEST
BaseMessage.RegisterExtension(_ORDERCANCELREQUEST.extensions_by_name['cmd'])
_ORDERCANCELREJECT.extensions_by_name['cmd'].message_type = _ORDERCANCELREJECT
BaseMessage.RegisterExtension(_ORDERCANCELREJECT.extensions_by_name['cmd'])
_ORDERCANCELREPLACEREQUEST.extensions_by_name['cmd'].message_type = _ORDERCANCELREPLACEREQUEST
BaseMessage.RegisterExtension(_ORDERCANCELREPLACEREQUEST.extensions_by_name['cmd'])
_NEWORDER.extensions_by_name['cmd'].message_type = _NEWORDER
BaseMessage.RegisterExtension(_NEWORDER.extensions_by_name['cmd'])
_ORDERSUBMITTED.extensions_by_name['cmd'].message_type = _ORDERSUBMITTED
BaseMessage.RegisterExtension(_ORDERSUBMITTED.extensions_by_name['cmd'])
_ORDERACCEPTED.extensions_by_name['cmd'].message_type = _ORDERACCEPTED
BaseMessage.RegisterExtension(_ORDERACCEPTED.extensions_by_name['cmd'])
_ORDERCANCELLED.extensions_by_name['cmd'].message_type = _ORDERCANCELLED
BaseMessage.RegisterExtension(_ORDERCANCELLED.extensions_by_name['cmd'])
_ORDERUPDATED.extensions_by_name['cmd'].message_type = _ORDERUPDATED
BaseMessage.RegisterExtension(_ORDERUPDATED.extensions_by_name['cmd'])
_SECURITYSTATUS.extensions_by_name['cmd'].message_type = _SECURITYSTATUS
BaseMessage.RegisterExtension(_SECURITYSTATUS.extensions_by_name['cmd'])
_ORDERREJECTED.extensions_by_name['cmd'].message_type = _ORDERREJECTED
BaseMessage.RegisterExtension(_ORDERREJECTED.extensions_by_name['cmd'])
_ORDERUPDATESUBMITTED.extensions_by_name['cmd'].message_type = _ORDERUPDATESUBMITTED
BaseMessage.RegisterExtension(_ORDERUPDATESUBMITTED.extensions_by_name['cmd'])
_ORDERCANCELSUBMITTED.extensions_by_name['cmd'].message_type = _ORDERCANCELSUBMITTED
BaseMessage.RegisterExtension(_ORDERCANCELSUBMITTED.extensions_by_name['cmd'])
_ORDERUPDATEREJECTED.extensions_by_name['cmd'].message_type = _ORDERUPDATEREJECTED
BaseMessage.RegisterExtension(_ORDERUPDATEREJECTED.extensions_by_name['cmd'])
_EXECUTIONREPORT2.extensions_by_name['cmd'].message_type = _EXECUTIONREPORT2
BaseMessage.RegisterExtension(_EXECUTIONREPORT2.extensions_by_name['cmd'])
_CUSTOMCOMMAND.extensions_by_name['cmd'].message_type = _CUSTOMCOMMAND
BaseMessage.RegisterExtension(_CUSTOMCOMMAND.extensions_by_name['cmd'])
_INFOEVENT.extensions_by_name['cmd'].message_type = _INFOEVENT
BaseMessage.RegisterExtension(_INFOEVENT.extensions_by_name['cmd'])
_OHLC.extensions_by_name['cmd'].message_type = _OHLC
BaseMessage.RegisterExtension(_OHLC.extensions_by_name['cmd'])
_TICK.extensions_by_name['cmd'].message_type = _TICK
BaseMessage.RegisterExtension(_TICK.extensions_by_name['cmd'])
_VALUESET.extensions_by_name['cmd'].message_type = _VALUESET
BaseMessage.RegisterExtension(_VALUESET.extensions_by_name['cmd'])
